### ISSUE TITLE
update pyxu name

### ISSUE THREAD

**Issue by VStergiop** [matthieumeo/cookiecutter-pycsou-plugin#2]
update pyxu name in setup.cfg file, line 64

**Comment by joanrue** [comment]
Many thanks @VStergiop ! These commits solve the issue: 
- https://github.com/matthieumeo/cookiecutter-pyxu/commit/74a6224ebab8bdbac563f91df94652a46e38e2be
- https://github.com/matthieumeo/cookiecutter-pyxu/commit/f0f5b0bdaa6cabeac16815e5658890ec02701e0a
- https://github.com/matthieumeo/cookiecutter-pyxu/commit/88a936d1c225c0455e748d7b7c7454d54e88a4f4
